--
-- Table structure for table book_detail
--

DROP TABLE IF EXISTS BOOK_CATEGORY;
CREATE TABLE BOOK_CATEGORY (
  ID int(11) unsigned NOT NULL AUTO_INCREMENT,
  NAME varchar(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID,NAME)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

--
-- Table structure for table book
--

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
  ID int(11) unsigned NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL UNIQUE,
  BOOK_CATEGORY_ID int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_book_bookcategoryid_idx (BOOK_CATEGORY_ID),
  CONSTRAINT fk_book_bookcategoryid FOREIGN KEY (BOOK_CATEGORY_ID) REFERENCES BOOK_CATEGORY (ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;